const state={token:localStorage.getItem("cinemax_token"),user:JSON.parse(localStorage.getItem("cinemax_user")||"null")};const $=id=>document.getElementById(id);
async function api(u,o={}){const h={"Content-Type":"application/json",...(o.headers||{})};if(state.token)h.Authorization="Bearer "+state.token;const r=await fetch(u,{...o,headers:h}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||"Request failed");return d}
function toast(x){const t=$("toast");if(!t)return;t.textContent=x;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
function card(m){return '<article class="movie-card"><a class="poster" href="movie.html?id='+m.id+'" style="background-image:url(\''+m.poster+'\')"><span class="rating">★ '+m.rating+'</span><span class="play-overlay">▶</span></a><div class="movie-info"><h3>'+m.title+'</h3><p>'+m.year+' • '+m.genre+'</p><div class="card-actions"><button onclick="location.href=\'movie.html?id='+m.id+'\'">View</button><button onclick="fav('+m.id+')">♡</button></div></div></article>'}
function render(ms){const g=$("movieGrid"),e=$("emptyState");if(g)g.innerHTML=ms.map(card).join("");if(e)e.hidden=!!ms.length}
async function load(){try{const q=new URLSearchParams({search:$("searchInput").value,genre:$("genreFilter").value});let ms=await api("/api/movies?"+q);const s=$("sortFilter").value;if(s==="year")ms.sort((a,b)=>b.year-a.year);if(s==="title")ms.sort((a,b)=>a.title.localeCompare(b.title));render(ms)}catch(e){toast(e.message)}}
async function loadFeatured(){try{const ms=await api("/api/movies");const row=$("featuredRow");if(row)row.innerHTML=ms.slice(0,3).map(m=>'<article class="featured-card" style="background-image:linear-gradient(90deg,#07080cee,#07080a44),url(\''+m.backdrop+'\')"><div><span class="kicker">FEATURED</span><h3>'+m.title+'</h3><p>'+m.year+' • '+m.genre+' • ★ '+m.rating+'</p><button class="primary" onclick="location.href=\'movie.html?id='+m.id+'\'">Watch details →</button></div></article>').join("")}catch(e){}}
async function fav(id){if(!state.token)return openAuth("login");try{await api("/api/favorites/"+id,{method:"POST"});toast("Added to My List")}catch(e){toast(e.message)}}
function openAuth(mode){$("authModal").classList.add("open");$("authForm").dataset.mode=mode;$("authTitle").textContent=mode==="login"?"Welcome Back":"Create Account";$("authSubmit").textContent=mode==="login"?"Login":"Create Account";$("name").style.display=mode==="login"?"none":"block"}
$("authForm").onsubmit=async e=>{e.preventDefault();const mode=e.currentTarget.dataset.mode,b={email:$("email").value,password:$("password").value};if(mode==="register")b.name=$("name").value;try{const d=await api("/api/auth/"+mode,{method:"POST",body:JSON.stringify(b)});state.token=d.token;state.user=d.user;localStorage.setItem("cinemax_token",d.token);localStorage.setItem("cinemax_user",JSON.stringify(d.user));closeModal();update();toast("Welcome to CineMax");loadCineMaxPersonal()}catch(x){toast(x.message)}}
function update(){if(!state.user)return;$("userButton").textContent="Hi, "+state.user.name.split(" ")[0];["profileLink","watchLink"].forEach(id=>{if($(id))$(id).hidden=false});if(state.user.role==="admin"&&$("adminLink"))$("adminLink").hidden=false}
async function loadCineMaxPersonal(){if(!state.token)return;try{const progress=await api("/api/progress"),cs=$("continueSection"),cr=$("continueRow");if(progress.length){cs.hidden=false;cr.innerHTML=progress.map(m=>cardProgress(m)).join("")}const rec=await api("/api/recommendations"),rs=$("recommendSection"),rr=$("recommendRow");if(rec.length){rs.hidden=false;rr.innerHTML=rec.map(card).join("")}}catch(e){}}
function cardProgress(m){const pct=Math.min(100,Math.round((m.seconds/(m.duration||1))*100));return '<article class="movie-card"><a class="poster" href="movie.html?id='+m.id+'" style="background-image:url(\''+m.poster+'\')"><span class="rating">★ '+m.rating+'</span><span class="play-overlay">▶</span><span class="progress"><i style="width:'+pct+'%"></i></span></a><div class="movie-info"><h3>'+m.title+'</h3><p>'+m.year+' • '+m.genre+'</p></div></article>'}
function closeModal(){document.querySelectorAll(".modal").forEach(m=>m.classList.remove("open"))}
$("searchInput").oninput=load;$("genreFilter").onchange=load;$("sortFilter").onchange=load;$("userButton").onclick=e=>{if(state.user){e.preventDefault();location.href="profile.html"}else{e.preventDefault();openAuth("login")}};$("signupButton").onclick=()=>openAuth("register");
document.querySelectorAll(".genre-grid button").forEach(b=>b.onclick=()=>{$("genreFilter").value=b.dataset.genre;load();document.getElementById("movies").scrollIntoView({behavior:"smooth"})});
$("themeButton").onclick=()=>{document.body.classList.toggle("light-mode");localStorage.setItem("cinemax_theme",document.body.classList.contains("light-mode")?"light":"dark")};
if(localStorage.getItem("cinemax_theme")==="light")document.body.classList.add("light-mode");
window.fav=fav;window.openAuth=openAuth;window.closeModal=closeModal;window.loadMovies=load;
update();load();loadFeatured();loadCineMaxPersonal();